#!/usr/bin/env python3
"""build_index.py — generate knowledge/INDEX.md from the graph nodes.

Stdlib-only. Groups nodes by type with status and last_verified columns and
prepends a graph-health line (% of nodes verified within 60 days). INDEX.md
is CI-built — never edited by hand. Deterministic for a fixed --today.

Usage: python3 scripts/build_index.py [--root DIR] [--today YYYY-MM-DD]
"""

import datetime
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import graph_check  # noqa: E402

TYPE_ORDER = ("capability", "workflow", "dependency", "convention", "gotcha", "decision")
HEALTH_WINDOW_DAYS = 60

HEADER = """# Knowledge Graph Index

> GENERATED by scripts/build_index.py — do not edit by hand.

"""


def graph_health(nodes, today):
    """Return (percent_or_None, fresh_count, total)."""
    total = len(nodes)
    if total == 0:
        return None, 0, 0
    fresh = 0
    for n in nodes:
        lv = n["data"].get("last_verified")
        if not lv:
            continue
        try:
            d = datetime.date.fromisoformat(str(lv))
        except ValueError:
            continue
        if (today - d).days <= HEALTH_WINDOW_DAYS:
            fresh += 1
    return round(100 * fresh / total), fresh, total


def render(nodes, today):
    pct, fresh, total = graph_health(nodes, today)
    out = [HEADER.rstrip("\n"), ""]
    if pct is None:
        out.append("Graph health: n/a (0 nodes).")
    else:
        out.append(f"Graph health: {pct}% verified within {HEALTH_WINDOW_DAYS} days "
                   f"({fresh} of {total} nodes).")
    by_type = {}
    for n in nodes:
        by_type.setdefault(n["data"].get("type") or "unknown", []).append(n)
    types = [t for t in TYPE_ORDER if t in by_type]
    types += sorted(t for t in by_type if t not in TYPE_ORDER)
    for t in types:
        out.append("")
        out.append(f"## {t}")
        out.append("")
        out.append("| Node | Title | Status | Last verified |")
        out.append("|------|-------|--------|---------------|")
        for n in sorted(by_type[t], key=lambda x: x["data"].get("id") or x["rel_id"]):
            d = n["data"]
            nid = d.get("id") or n["rel_id"]
            out.append(f"| [{nid}]({nid}.md) | {d.get('title', '')} "
                       f"| {d.get('status', '')} | {d.get('last_verified', '')} |")
    if not types:
        out.append("")
        out.append("No nodes yet.")
    return "\n".join(out) + "\n"


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    root = "."
    today = datetime.date.today()
    while argv:
        arg = argv.pop(0)
        if arg == "--root" and argv:
            root = argv.pop(0)
        elif arg == "--today" and argv:
            try:
                today = datetime.date.fromisoformat(argv.pop(0))
            except ValueError:
                print("build_index.py: --today must be YYYY-MM-DD", file=sys.stderr)
                return 1
        else:
            print("usage: build_index.py [--root DIR] [--today YYYY-MM-DD]", file=sys.stderr)
            return 1
    root = Path(root)
    knowledge = root / "knowledge"
    if not knowledge.is_dir():
        print(f"{knowledge}:1: error: knowledge/ directory not found", file=sys.stderr)
        return 1
    nodes, errors = graph_check.load_nodes(root)
    if errors:
        for path, line, msg in errors:
            print(f"{path}:{line}: error: {msg}", file=sys.stderr)
        return 1
    (knowledge / "INDEX.md").write_text(render(nodes, today), encoding="utf-8", newline="\n")
    print(f"build_index: wrote knowledge/INDEX.md ({len(nodes)} node(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
